#!/bin/bash

. ~/git-sh-prompt
PROMPT_COMMAND='__git_ps1 "\n$(printf '[31m━%.s' $(seq 1 $COLUMNS))\r\033[1C\033[36m 🖿 \033[37m:\033[33m \w\033[m"  " \n\033[01;32m BOOEY\033[37m@\033[01;32m66MHz.ca\033[37m \\\$ "' 


