#!/bin/bash

. ~/git-sh-prompt
PROMPT_COMMAND='__git_ps1 "\n[31m┏$(printf '[31m━%.s' $(seq 1 $[$COLUMNS-1]))\r\033[2C\033[36m 🖿 \033[37m:\033[33m \w\033[m"  " \n\033[01;31m┗━ $(nonzero_return) \033[37m \\\$: "' 


